function Hd2 = filtro_2
%FILTRO_2 Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 18-Mar-2016 10:29:02
%

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N   = 20;    % Order
Fc1 = 4900;  % First Cutoff Frequency
Fc2 = 5100;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h = fdesign.bandstop('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd2 = design(h, 'butter');

% [EOF]
